In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [6]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [7]:
def derivativeSig(z):
  return sig(z)*(1-sig(z))

In [8]:
# one hidden layer weights
wh = 2* np.random.random((2, 2)) - 1
bh = 2* np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1,1)) - 1
lr = 0.1

In [9]:
output0 = X
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden, wo) + bo)
output

array([[0.71241581],
       [0.67332733],
       [0.68457585],
       [0.64193477]])

In [10]:
for iter in range(10000):
  output0 = X
  input_Hidden = np.dot(output0, wh) + bh
  output_Hidden = sig(input_Hidden)
  input_For_output_Layer = np.dot(output_Hidden, wo) + bo
  output = sig(input_For_output_Layer)

  first_term_output_layer = output-Y
  second_term_output_layer = derivativeSig(input_For_output_Layer)
  first_two_output_layer = first_term_output_layer*second_term_output_layer

  first_term_hidden_layer = np.dot(first_two_output_layer, wo.T)
  second_term_hidden_layer = derivativeSig(input_Hidden)
  first_two_hidden_layer = first_term_output_layer*second_term_output_layer

  changes_output = np.dot(output_Hidden.T, first_two_output_layer)
  changes_output_bias = np.sum(first_two_output_layer, axis=0, keepdims=True)

  changes_hidden = np.dot(output0.T, first_two_hidden_layer)
  changes_hidden_bias = np.sum(first_two_hidden_layer, axis=0, keepdims=True)

  wo = wo - lr*changes_output
  bo = bo - lr*changes_output_bias

  wh = wh - lr*changes_hidden
  bh = bh - lr*changes_hidden_bias

output0 = X
input_Hidden = np.dot(output0, wh) + bh
output_Hidden = sig(input_Hidden)
input_For_output_Layer = np.dot(output_Hidden, wo) + bo
output = sig(input_For_output_Layer)

output, wh, bh, wo, bo

(array([[0.02809133],
        [0.33293403],
        [0.33293403],
        [0.33293403]]),
 array([[73.49279809, 74.17706752],
        [73.89576875, 75.12432079]]),
 array([[-4.00308467, -3.87415549]]),
 array([[2.40696314],
        [0.4951297 ]]),
 array([[-3.59703744]]))